package com.get.edgepay.fms.common;

public enum FMSRuleConstant {

	RULE_ENTITY_EMAIL("EMAIL"), RULE_ENTITY_CARDNO("CARDNUMBER"), RULE_ENTITY_STREET_ADDRESS("STREETADDRESS"),  
	RULE_ENTITY_IP("IPADDRESS"), RULE_ENTITY_WORD("WORDBLOCK"), RULE_ENTITY_MAX_AMOUNT("MAXAMOUNTLIMIT"),
	RULE_ENTITY_ORDER_LIMIT_CARD("CARDUSELIMIT"), RULE_ENTITY_ORDER_LIMIT_IP("IPUSELIMIT"),
	
	RULE_ACCESSMODE_PUBLIC("PUBLIC"), RULE_ACCESSMODE_PRIVATE("PRIVATE"),

	RULE_ACTION_REVIEW("REVIEW"), RULE_ACTION_DECLINE("DECLINE"),

	RULE_ACTION_REVIEW_STATUS("R"), RULE_ACTION_DECLINE_STATUS("D");

	private String value;

	private FMSRuleConstant(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
